package com.example.hibernate.model;
// Generated 23 ene 2025, 16:27:48 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Cicloformativo generated by hbm2java
 */
@Entity
@Table(name="cicloformativo"
)
public class Ciclo  implements java.io.Serializable {


     private Integer idCiclo;
     private String nombre;
     private Integer horas;

    public Ciclo() {
    }

    public Ciclo(String nombreCiclo, Integer horas) {
       this.nombre = nombreCiclo;
       this.horas = horas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCiclo", unique=true, nullable=false)
    public Integer getIdCiclo() {
        return this.idCiclo;
    }
    
    public void setIdCiclo(Integer idCiclo) {
        this.idCiclo = idCiclo;
    }

    
    @Column(name="nombreCiclo", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombreCiclo) {
        this.nombre = nombreCiclo;
    }

    
    @Column(name="horas")
    public Integer getHoras() {
        return this.horas;
    }
    
    public void setHoras(Integer horas) {
        this.horas = horas;
    }

    @Override
    public String toString() {
        return "CicloFormativo [idCiclo=" + idCiclo + ", nombreCiclo=" + nombre + ", horas=" + horas + "]";
    }




}


