package com.example.hibernate.model;
// Generated 23 ene 2025, 16:27:48 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
@NamedQuery(name = "Profesor_findByNombreApe1Ap2", 
  query = "select p from Profesor p where p.nombre = :nombre and p.ape1 =:apellido1 and p.ape2=: apellido2")
@Entity
@Table(name="profesor"
)
public class Profesor  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String ape1;
     private String ape2;
     private String tipoFuncionario;
     private Set<Modulo> modulos = new HashSet<Modulo>(0);

    public Profesor() {
    }

	
    public Profesor(String nombre, String ape1, String ape2) {
        this.nombre = nombre;
        this.ape1 = ape1;
        this.ape2 = ape2;
    }
    public Profesor(String nombre, String ape1, String ape2, String tipoFuncionario, Set<Modulo> modulos) {
       this.nombre = nombre;
       this.ape1 = ape1;
       this.ape2 = ape2;
       this.tipoFuncionario = tipoFuncionario;
       this.modulos = modulos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ape1", nullable=false, length=255)
    public String getApe1() {
        return this.ape1;
    }
    
    public void setApe1(String ape1) {
        this.ape1 = ape1;
    }

    
    @Column(name="ape2", nullable=false, length=255)
    public String getApe2() {
        return this.ape2;
    }
    
    public void setApe2(String ape2) {
        this.ape2 = ape2;
    }

    
    @Column(name="tipoFuncionario", length=100)
    public String getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    public void setTipoFuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }

@Override
    public String toString() {
        return "Profesor [id=" + id + ", nombre=" + nombre + ", ape1=" + ape1 + ", ape2=" + ape2 + ", tipoFuncionario="
                + tipoFuncionario + "]";
    }


@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="profesormodulo", catalog="instituto", joinColumns = { 
        @JoinColumn(name="idProfesor", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idModulo", nullable=false) })
    public Set<Modulo> getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set<Modulo> modulos) {
        this.modulos = modulos;
    }




}


