/*
 * Copyright 2023 Módulo Programación
 * https://www.edu.xunta.gal/fpadistancia/
 */

/**
 *
 * @author xdGHOSTbx
 */
public class Encuesta extends javax.swing.JFrame {

  /**
   * Creates new form Encuesta
   */
  public Encuesta() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenu1 = new javax.swing.JMenu();
    btnHacerEncuesta = new javax.swing.JButton();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMArchivo = new javax.swing.JMenu();
    jMEncuesta = new javax.swing.JMenu();
    jMHacerEncuesta = new javax.swing.JMenuItem();
    jMAyuda = new javax.swing.JMenu();

    jMenu1.setText("jMenu1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnHacerEncuesta.setText("Hacer encuesta");
    btnHacerEncuesta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHacerEncuestaActionPerformed(evt);
      }
    });

    jMArchivo.setText("Archivo");
    jMenuBar1.add(jMArchivo);

    jMEncuesta.setText("Encuesta");

    jMHacerEncuesta.setText("Hacer encuesta");
    jMHacerEncuesta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMHacerEncuestaActionPerformed(evt);
      }
    });
    jMEncuesta.add(jMHacerEncuesta);

    jMenuBar1.add(jMEncuesta);

    jMAyuda.setText("Ayuda");
    jMenuBar1.add(jMAyuda);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addComponent(btnHacerEncuesta)
        .addContainerGap(248, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addComponent(btnHacerEncuesta)
        .addContainerGap(226, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMHacerEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMHacerEncuestaActionPerformed
    new formularioTest().setVisible(true);
  }//GEN-LAST:event_jMHacerEncuestaActionPerformed

  private void btnHacerEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerEncuestaActionPerformed
    formularioTest miformulario = new formularioTest();
    miformulario.setVisible(true);
  }//GEN-LAST:event_btnHacerEncuestaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Encuesta().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnHacerEncuesta;
  private javax.swing.JMenu jMArchivo;
  private javax.swing.JMenu jMAyuda;
  private javax.swing.JMenu jMEncuesta;
  private javax.swing.JMenuItem jMHacerEncuesta;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  // End of variables declaration//GEN-END:variables
}
