/*
 * Copyright 2023 Módulo Programación
 * https://www.edu.xunta.gal/fpadistancia/
 */
package appHotel;

import javax.swing.JOptionPane;

/**
 *
 * @author xdGHOSTbx
 */
public class Menu extends javax.swing.JFrame {

  /**
   * Creates new form Menu
   */
  public Menu() {
    initComponents();
  }
  //titulo por defecto para el cuadro de dialogo de las opciones sin funcionalidad
  String tituloAlarma = "";
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSeparator1 = new javax.swing.JSeparator();
    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    BTCuba = new javax.swing.JButton();
    BTHabana = new javax.swing.JButton();
    BTMadrid = new javax.swing.JButton();
    BTBarcelona = new javax.swing.JButton();
    jSeparator2 = new javax.swing.JSeparator();
    BTSalir = new javax.swing.JButton();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMArchivo = new javax.swing.JMenu();
    jMReseva = new javax.swing.JMenu();
    jMeReservarHotel = new javax.swing.JMenuItem();
    jMSobreNosotros = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Gestión Hotelera");
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Noto Serif", 3, 24)); // NOI18N
    jLabel1.setText("GESTION HOTELERA");

    BTCuba.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    BTCuba.setText("Salón Cuba");
    BTCuba.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BTCubaActionPerformed(evt);
      }
    });

    BTHabana.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    BTHabana.setText("Salón Habana");
    BTHabana.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BTHabanaActionPerformed(evt);
      }
    });

    BTMadrid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    BTMadrid.setText("Salón Madrid");
    BTMadrid.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BTMadridActionPerformed(evt);
      }
    });

    BTBarcelona.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    BTBarcelona.setText("Salón Barcelona");
    BTBarcelona.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BTBarcelonaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(37, 37, 37)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(BTHabana, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(BTMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(BTCuba, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(BTBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(42, 42, 42))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(34, 34, 34)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(BTCuba, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(BTHabana, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(BTBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(BTMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(20, 20, 20))
    );

    BTSalir.setText("Salir");
    BTSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BTSalirActionPerformed(evt);
      }
    });

    jMArchivo.setText("Archivo");
    jMArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jMArchivoMouseClicked(evt);
      }
    });
    jMArchivo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMArchivoActionPerformed(evt);
      }
    });
    jMenuBar1.add(jMArchivo);

    jMReseva.setText("Reservas");

    jMeReservarHotel.setText("Reservar Hotel");
    jMeReservarHotel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMeReservarHotelActionPerformed(evt);
      }
    });
    jMReseva.add(jMeReservarHotel);

    jMenuBar1.add(jMReseva);

    jMSobreNosotros.setText("Sobre Nosotros");
    jMSobreNosotros.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jMSobreNosotrosMouseClicked(evt);
      }
    });
    jMenuBar1.add(jMSobreNosotros);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(106, 106, 106))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(BTSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(BTSalir)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMArchivoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jMArchivoActionPerformed

  private void jMArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMArchivoMouseClicked
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Esta funcionalidad aun no está disponible", tituloAlarma, JOptionPane.WARNING_MESSAGE);
  }//GEN-LAST:event_jMArchivoMouseClicked

  private void jMSobreNosotrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSobreNosotrosMouseClicked
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Esta funcionalidad aun no está disponible", tituloAlarma, JOptionPane.WARNING_MESSAGE);
  }//GEN-LAST:event_jMSobreNosotrosMouseClicked

  private void BTCubaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCubaActionPerformed
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Esta funcionalidad aun no está disponible", tituloAlarma, JOptionPane.WARNING_MESSAGE);
  }//GEN-LAST:event_BTCubaActionPerformed

  private void BTMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMadridActionPerformed
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Esta funcionalidad aun no está disponible", tituloAlarma, JOptionPane.WARNING_MESSAGE);
  }//GEN-LAST:event_BTMadridActionPerformed

  private void BTBarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBarcelonaActionPerformed
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Esta funcionalidad aun no está disponible", tituloAlarma, JOptionPane.WARNING_MESSAGE);
  }//GEN-LAST:event_BTBarcelonaActionPerformed

  private void BTSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalirActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_BTSalirActionPerformed

  private void BTHabanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTHabanaActionPerformed
    // TODO add your handling code here:
    salonHabana newSalon = new salonHabana();
    newSalon.setVisible(true);
  }//GEN-LAST:event_BTHabanaActionPerformed

  private void jMeReservarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeReservarHotelActionPerformed
    // TODO add your handling code here:
    new salonHabana().setVisible(true);
  }//GEN-LAST:event_jMeReservarHotelActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Menu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton BTBarcelona;
  private javax.swing.JButton BTCuba;
  private javax.swing.JButton BTHabana;
  private javax.swing.JButton BTMadrid;
  private javax.swing.JButton BTSalir;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JMenu jMArchivo;
  private javax.swing.JMenu jMReseva;
  private javax.swing.JMenu jMSobreNosotros;
  private javax.swing.JMenuItem jMeReservarHotel;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  // End of variables declaration//GEN-END:variables
}
