/*
 * Copyright 2023 Módulo Programación
 * https://www.edu.xunta.gal/fpadistancia/
 */
package appHotel;

import javax.swing.JOptionPane;

/**
 *
 * @author xdGHOSTbx
 */
public class salonHabana extends javax.swing.JFrame {

  /**
   * Creates new form salonHabana
   */
  public salonHabana() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    grupoEventos = new javax.swing.ButtonGroup();
    grupoCocina = new javax.swing.ButtonGroup();
    siNo = new javax.swing.ButtonGroup();
    BTcancelar = new javax.swing.JButton();
    BTreserva = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    TFnombre = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    TFtlf = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    TFmail = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel4 = new javax.swing.JLabel();
    SPfecha = new javax.swing.JSpinner();
    jLabel5 = new javax.swing.JLabel();
    RBjornada = new javax.swing.JRadioButton();
    RBcongreso = new javax.swing.JRadioButton();
    RBbanquete = new javax.swing.JRadioButton();
    jLabel7 = new javax.swing.JLabel();
    SPasistentes = new javax.swing.JSpinner();
    jLabel6 = new javax.swing.JLabel();
    RBbufe = new javax.swing.JRadioButton();
    RBcarta = new javax.swing.JRadioButton();
    RBchef = new javax.swing.JRadioButton();
    RBnoPrecisa = new javax.swing.JRadioButton();
    jSeparator2 = new javax.swing.JSeparator();
    jSeparator3 = new javax.swing.JSeparator();
    jPanel2 = new javax.swing.JPanel();
    jornadas = new javax.swing.JLabel();
    SPjornadas = new javax.swing.JSpinner();
    hab = new javax.swing.JLabel();
    si = new javax.swing.JRadioButton();
    no = new javax.swing.JRadioButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    BTcancelar.setText("Cancelar");
    BTcancelar.setToolTipText("vovler atras");
    BTcancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BTcancelarActionPerformed(evt);
      }
    });

    BTreserva.setText("Reservar");
    BTreserva.setToolTipText("realizar reserva");
    BTreserva.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    BTreserva.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BTreservaActionPerformed(evt);
      }
    });

    jLabel1.setText("Nombre");

    TFnombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    TFnombre.setToolTipText("espacio para introducir el nombre");

    jLabel2.setText("Tlf Contacto");

    TFtlf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    TFtlf.setToolTipText("espacio para introducir el num telefonico");

    jLabel3.setText("e-mail");

    TFmail.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    TFmail.setToolTipText("espacio para introducir el mail");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel1)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(TFtlf, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(TFmail))
          .addComponent(TFnombre))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(TFtlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3)
          .addComponent(TFmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel4.setText("Fecha del Evento");

    SPfecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1726325580000L), null, null, java.util.Calendar.DAY_OF_MONTH));
    SPfecha.setToolTipText("fecha del evento");

    jLabel5.setText("Tipo de Evento");

    grupoEventos.add(RBjornada);
    RBjornada.setText("Jornada");
    RBjornada.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        RBjornadaActionPerformed(evt);
      }
    });
    RBjornada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        RBjornadaPropertyChange(evt);
      }
    });

    grupoEventos.add(RBcongreso);
    RBcongreso.setText("Congreso");
    RBcongreso.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        RBcongresoActionPerformed(evt);
      }
    });

    grupoEventos.add(RBbanquete);
    RBbanquete.setSelected(true);
    RBbanquete.setText("Banquete");
    RBbanquete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        RBbanqueteActionPerformed(evt);
      }
    });

    jLabel7.setText("Asistentes");

    SPasistentes.setModel(new javax.swing.SpinnerNumberModel(1, null, 50, 1));
    SPasistentes.setToolTipText("numero de asistentes");

    jLabel6.setText("Tipo de Cocina");

    grupoCocina.add(RBbufe);
    RBbufe.setSelected(true);
    RBbufe.setText("Bufé");

    grupoCocina.add(RBcarta);
    RBcarta.setText("Carta");

    grupoCocina.add(RBchef);
    RBchef.setText("Cita con el Chef");

    grupoCocina.add(RBnoPrecisa);
    RBnoPrecisa.setText("No precisa");
    RBnoPrecisa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        RBnoPrecisaActionPerformed(evt);
      }
    });

    jornadas.setLabelFor(jPanel2);
    jornadas.setText("Número de Jornadas");
    jornadas.setEnabled(false);

    SPjornadas.setModel(new javax.swing.SpinnerNumberModel(1, null, 50, 1));
    SPjornadas.setToolTipText("numero de jornadas");
    SPjornadas.setEnabled(false);

    hab.setText("Habitaciones para asistentes?");
    hab.setEnabled(false);

    siNo.add(si);
    si.setText("Si");
    si.setEnabled(false);

    siNo.add(no);
    no.setText("No");
    no.setEnabled(false);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(si)
            .addGap(29, 29, 29)
            .addComponent(no)
            .addGap(27, 27, 27))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jornadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPjornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(hab))
            .addContainerGap(24, Short.MAX_VALUE))))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jornadas)
          .addComponent(SPjornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(hab)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(si)
          .addComponent(no))
        .addContainerGap(8, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(39, 39, 39)
        .addComponent(jLabel6)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(RBnoPrecisa)
          .addComponent(RBchef)
          .addComponent(RBcarta)
          .addComponent(RBbufe))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(jLabel5)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(RBcongreso)
              .addComponent(RBbanquete)
              .addComponent(RBjornada))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(30, 30, 30))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jSeparator3)
              .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(SPfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(SPasistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(BTcancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTreserva)
                .addGap(8, 8, 8)))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(SPfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7)
          .addComponent(SPasistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(RBbanquete)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(RBjornada)
              .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(RBcongreso)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addGap(18, 18, 18)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(RBbufe)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(RBcarta)
          .addComponent(jLabel6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(RBchef)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(RBnoPrecisa)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(BTcancelar)
          .addComponent(BTreserva))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void BTcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcancelarActionPerformed
    // TODO add your handling code here:
    setVisible(false);
  }//GEN-LAST:event_BTcancelarActionPerformed

  private void BTreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTreservaActionPerformed
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Su reserva se ha realizado con éxito", "", JOptionPane.INFORMATION_MESSAGE);
    setVisible(false);
  }//GEN-LAST:event_BTreservaActionPerformed

  private void RBcongresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBcongresoActionPerformed
    // TODO add your handling code here:
    //lo activamos
    jornadas.setEnabled(true);
    SPjornadas.setEnabled(true);
    no.setEnabled(true);
    si.setEnabled(true);
    hab.setEnabled(true);
  }//GEN-LAST:event_RBcongresoActionPerformed

  private void RBnoPrecisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBnoPrecisaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_RBnoPrecisaActionPerformed

  private void RBjornadaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_RBjornadaPropertyChange
    // TODO add your handling code here:
  }//GEN-LAST:event_RBjornadaPropertyChange

  private void RBjornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBjornadaActionPerformed
    // TODO add your handling code here:
    //lo desactivamos
    jornadas.setEnabled(false);
    SPjornadas.setEnabled(false);
    no.setEnabled(false);
    si.setEnabled(false);
    hab.setEnabled(false);
    
  }//GEN-LAST:event_RBjornadaActionPerformed

  private void RBbanqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBbanqueteActionPerformed
    // TODO add your handling code here:
    //lo desactivamos
    jornadas.setEnabled(false);
    SPjornadas.setEnabled(false);
    no.setEnabled(false);
    si.setEnabled(false);
    hab.setEnabled(false);
  }//GEN-LAST:event_RBbanqueteActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(salonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(salonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(salonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(salonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new salonHabana().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton BTcancelar;
  private javax.swing.JButton BTreserva;
  private javax.swing.JRadioButton RBbanquete;
  private javax.swing.JRadioButton RBbufe;
  private javax.swing.JRadioButton RBcarta;
  private javax.swing.JRadioButton RBchef;
  private javax.swing.JRadioButton RBcongreso;
  private javax.swing.JRadioButton RBjornada;
  private javax.swing.JRadioButton RBnoPrecisa;
  private javax.swing.JSpinner SPasistentes;
  private javax.swing.JSpinner SPfecha;
  private javax.swing.JSpinner SPjornadas;
  private javax.swing.JTextField TFmail;
  private javax.swing.JTextField TFnombre;
  private javax.swing.JTextField TFtlf;
  private javax.swing.ButtonGroup grupoCocina;
  private javax.swing.ButtonGroup grupoEventos;
  private javax.swing.JLabel hab;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JLabel jornadas;
  private javax.swing.JRadioButton no;
  private javax.swing.JRadioButton si;
  private javax.swing.ButtonGroup siNo;
  // End of variables declaration//GEN-END:variables
}
