package com.example.hibernate.model;
// Generated 7 mar 2025, 17:29:40 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.math.BigDecimal;
//import java.sql.Timestamp;
import java.time.*;

/**
 * AccMovement generated by hbm2java
 */
@Entity
@Table(name="acc_movement"
)
public class AccMovement  implements java.io.Serializable {


     private Integer accountMovId;
     private Account accountByAccountDestId;
     private Account accountByAccountOriginId;
     private BigDecimal amount;
    // private Timestamp datetime;
    private LocalDateTime datetime;

    public AccMovement() {
    }

    public AccMovement(Account accountByAccountDestId, Account accountByAccountOriginId, BigDecimal amount, LocalDateTime datetime) {
       this.accountByAccountDestId = accountByAccountDestId;
       this.accountByAccountOriginId = accountByAccountOriginId;
       this.amount = amount;
       this.datetime = datetime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ACCOUNT_MOV_ID", unique=true, nullable=false)
    public Integer getAccountMovId() {
        return this.accountMovId;
    }
    
    public void setAccountMovId(Integer accountMovId) {
        this.accountMovId = accountMovId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_DEST_ID", nullable=false)
    public Account getAccountByAccountDestId() {
        return this.accountByAccountDestId;
    }
    
    public void setAccountByAccountDestId(Account accountByAccountDestId) {
        this.accountByAccountDestId = accountByAccountDestId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_ORIGIN_ID", nullable=false)
    public Account getAccountByAccountOriginId() {
        return this.accountByAccountOriginId;
    }
    
    public void setAccountByAccountOriginId(Account accountByAccountOriginId) {
        this.accountByAccountOriginId = accountByAccountOriginId;
    }

    
    @Column(name="AMOUNT", nullable=false, precision=19, scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATETIME", nullable=false, length=19)
    public LocalDateTime getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(LocalDateTime datetime) {
        this.datetime = datetime;
    }

    @Override
    public String toString() {
        return "AccMovement [accountMovId=" + accountMovId + ", amount=" + amount + ", datetime=" + datetime + "]";
    }


    

}


