package com.example.hibernate.model;
// Generated 7 mar 2025, 17:29:40 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Dept generated by hbm2java
 */
@Entity
@Table(name="dept"
)
public class Dept  implements java.io.Serializable {


     private Integer deptno;
     private String dname;
     private String loc;
     private Set<Empleado> emps = new HashSet<Empleado>(0);

    public Dept() {
    }

    public Dept(String dname, String loc, Set<Empleado> emps) {
       this.dname = dname;
       this.loc = loc;
       this.emps = emps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="DEPTNO", unique=true, nullable=false)
    public Integer getDeptno() {
        return this.deptno;
    }
    
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    
    @Column(name="DNAME", length=20)
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }

    
    @Column(name="LOC", length=20)
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dept")
    public Set<Empleado> getEmps() {
        return this.emps;
    }
    
    public void setEmps(Set<Empleado> emps) {
        this.emps = emps;
    }




}


