package com.example.hibernate.model;
// Generated 7 mar 2025, 17:29:40 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name="project"
)
public class Project  implements java.io.Serializable {


     private Integer projno;
     private String projname;
     private Set<Empleado> emps = new HashSet<Empleado>(0);

    public Project() {
    }

	
    public Project(String projname) {
        this.projname = projname;
    }
    public Project(String projname, Set<Empleado> emps) {
       this.projname = projname;
       this.emps = emps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PROJNO", unique=true, nullable=false)
    public Integer getProjno() {
        return this.projno;
    }
    
    public void setProjno(Integer projno) {
        this.projno = projno;
    }

    
    @Column(name="PROJNAME", nullable=false, length=50)
    public String getProjname() {
        return this.projname;
    }
    
    public void setProjname(String projname) {
        this.projname = projname;
    }

@ManyToMany(mappedBy ="projects", fetch=FetchType.LAZY)
    //Se elimina este fragmento para que no se cree la tabla intermedia 2 veces, matiene el lado propietario empleado gracias al mappedBy
    //@JoinTable(name="project_emp", catalog="empresa", joinColumns = { 
        //@JoinColumn(name="PROJECTNO", nullable=false/*, updatable=false */) }, inverseJoinColumns = { 
        //@JoinColumn(name="EMPNO", nullable=false/*, updatable=false */) })
    public Set<Empleado> getEmps() {
        return this.emps;
    }
    
    public void setEmps(Set<Empleado> emps) {
        this.emps = emps;
    }




}


