package com.example.hibernate.model;
// Generated 24 ene 2025, 13:13:02 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Cicloformativo generated by hbm2java
 */
@Entity
@Table(name="cicloformativo"
)
public class Cicloformativo  implements java.io.Serializable {


     private Integer idCiclo;
     private String nombreCiclo;
     private Integer horas;

    public Cicloformativo() {
    }

    public Cicloformativo(String nombreCiclo, Integer horas) {
       this.nombreCiclo = nombreCiclo;
       this.horas = horas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCiclo", unique=true, nullable=false)
    public Integer getIdCiclo() {
        return this.idCiclo;
    }
    
    public void setIdCiclo(Integer idCiclo) {
        this.idCiclo = idCiclo;
    }

    
    @Column(name="nombreCiclo", length=100)
    public String getNombreCiclo() {
        return this.nombreCiclo;
    }
    
    public void setNombreCiclo(String nombreCiclo) {
        this.nombreCiclo = nombreCiclo;
    }

    
    @Column(name="horas")
    public Integer getHoras() {
        return this.horas;
    }
    
    public void setHoras(Integer horas) {
        this.horas = horas;
    }




}


