package com.example.hibernate.model;
// Generated 24 ene 2025, 13:13:02 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="provincia"
)
public class Provincia  implements java.io.Serializable {


     private int idProvincia;
     private Comunidadautonoma comunidadautonoma;
     private String nombre;
     private Set<Direccion> direccions = new HashSet<Direccion>(0);

    public Provincia() {
    }

	
    public Provincia(int idProvincia, Comunidadautonoma comunidadautonoma) {
        this.idProvincia = idProvincia;
        this.comunidadautonoma = comunidadautonoma;
    }
    public Provincia(int idProvincia, Comunidadautonoma comunidadautonoma, String nombre, Set<Direccion> direccions) {
       this.idProvincia = idProvincia;
       this.comunidadautonoma = comunidadautonoma;
       this.nombre = nombre;
       this.direccions = direccions;
    }
   
     @Id 

    
    @Column(name="idProvincia", unique=true, nullable=false)
    public int getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(int idProvincia) {
        this.idProvincia = idProvincia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCA", nullable=false)
    public Comunidadautonoma getComunidadautonoma() {
        return this.comunidadautonoma;
    }
    
    public void setComunidadautonoma(Comunidadautonoma comunidadautonoma) {
        this.comunidadautonoma = comunidadautonoma;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provincia")
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


