/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sources;

import javax.swing.JOptionPane;

import java.sql.*;
import baseDatos.conBase;
import Sources.registro;
import Sources.test;
/**
 *
 * @author USER
 */

public class reg_form extends javax.swing.JFrame {
    
    private static Connection con;
    private static final String user="dani";
    private static final String pasw="3113";
    private static final String url="jdbc:mysql://localhost:3306/registro";
    
    
    boolean acceso = false;
    
    
    /**
     * Creates new form reg_form
     */
    public reg_form() {
        initComponents();
    }
    //metodos del formulario
    public void limpiar(){
      tf_nombre.setText("");
      tf_contra.setText("");
    }

    //metodo para obtener los datos del formulario
    public void registrar(){
        String nombre = tf_nombre.getText();
        String contraseña = tf_contra.getText();
        String consulta = "INSERT INTO usuarios (usuario,contraseña) VALUES ('"+nombre.toLowerCase()+"','"+contraseña+"')";

        // Validar que los campos no estén vacíos
        if (nombre.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
      /*
        // Validar que la fecha tenga un formato válido 
        if (!fecha.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato YYYY-MM-DD", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
      */
        // Validar que la contraseña tenga una longitud mínima (por ejemplo, 6 caracteres)
        if (contraseña.length() < 6) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            //Se inicia la consulta
            Statement st = (Statement) con.createStatement();
            st.executeUpdate(consulta);
            JOptionPane.showMessageDialog(this, "Registro exitoso");
            limpiar();
        } catch (SQLException e) {
            System.err.println("Error al registrar: " + e.getMessage());
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    public void acceso (){
        conBase.conector();
        Connection con = conBase.getConnection();
        String usuario = tf_nombre.getText();
        String pasw = tf_contra.getText();
        String consulta = "SELECT usuario,contraseña FROM usuarios WHERE usuario = ? AND contraseña = ?";
        
        if (usuario.isEmpty() || pasw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (con != null){
          try{
            PreparedStatement ps = con.prepareStatement(consulta);
            ps.setString(1, usuario);
            ps.setString(2, pasw);
            try(ResultSet rs = ps.executeQuery();){
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Acceso concedido");
                    acceso = true;
                } else {
                    JOptionPane.showMessageDialog(this, "Acceso denegado");
                }
            }
          }catch (SQLException e) {
                System.err.println("Error al registrar: " + e.getMessage());
                JOptionPane.showMessageDialog(this, e);
          } finally {
            conBase.closeConnection();
          }
        }else {
          JOptionPane.showMessageDialog(this,"No se pudo establecer conexion con la base de datos");
        }
        

        tf_contra.setText("");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        bt_enviar = new javax.swing.JButton();
        bt_limpiar = new javax.swing.JButton();
        bt_acceso = new javax.swing.JButton();
        tf_contra = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jm_registro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        bt_enviar.setText("Registro");
        bt_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarActionPerformed(evt);
            }
        });

        bt_limpiar.setText("Limpiar");
        bt_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpiarActionPerformed(evt);
            }
        });

        bt_acceso.setText("Acceder");
        bt_acceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_accesoActionPerformed(evt);
            }
        });

        jMenu1.setText("Entrar");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registro");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jm_registro.setText("Registrarse");
        jm_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_registroActionPerformed(evt);
            }
        });
        jMenu2.add(jm_registro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_acceso)
                        .addGap(18, 18, 18)
                        .addComponent(bt_limpiar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_enviar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_contra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_acceso)
                    .addComponent(bt_limpiar)
                    .addComponent(bt_enviar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_bt_limpiarActionPerformed

    private void bt_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarActionPerformed
;
        
        //tambien se puede crear así
        new test(this,true).setVisible(true);
        
    }//GEN-LAST:event_bt_enviarActionPerformed

    private void bt_accesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_accesoActionPerformed
        // TODO add your handling code here:
        acceso();
        if(acceso){
            new registro().setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_bt_accesoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        new test(this, true).setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jm_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_registroActionPerformed
        // TODO add your handling code here:
        new test(this,true).setVisible(true);
    }//GEN-LAST:event_jm_registroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reg_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reg_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reg_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reg_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reg_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_acceso;
    private javax.swing.JButton bt_enviar;
    private javax.swing.JButton bt_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jm_registro;
    private javax.swing.JPasswordField tf_contra;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables
}
