/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.WindowAdapter;
import  java.awt.event.WindowEvent;

/**
 *
 * @author USER
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        agregarListenerAlCierre();
        
    }
    private void agregarListenerAlCierre(){
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                mostrarAlerta();
            }
        });
    }
    private void mostrarAlerta(){
        JOptionPane.showMessageDialog(this, "TIENES QUE RESPONDER A LA PREGUNTA!!!", tituloAlarma, JOptionPane.WARNING_MESSAGE);
    }

    String tituloAlarma = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTSi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        BTNo6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BTNo2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        BTNo5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        BTNo3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        BTNo4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        BTNo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BTSi.setBackground(new java.awt.Color(0, 204, 0));
        BTSi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTSi.setForeground(new java.awt.Color(255, 255, 255));
        BTSi.setText("SI");
        BTSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Merece este alumno aprobar la asignatura directamente?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(BTSi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTSi)
                .addGap(16, 16, 16))
        );

        jPanel2.setLayout(null);

        BTNo6.setBackground(new java.awt.Color(204, 0, 0));
        BTNo6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTNo6.setText("NO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(BTNo6)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNo6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BTNo6.setVisible(false);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(300, 110, 100, 51);

        BTNo2.setBackground(new java.awt.Color(204, 0, 0));
        BTNo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTNo2.setText("NO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        BTNo2.setVisible(false);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(310, 40, 84, 51);

        BTNo5.setBackground(new java.awt.Color(204, 0, 0));
        BTNo5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTNo5.setText("NO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(BTNo5)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(BTNo5))
        );

        BTNo5.setVisible(false);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(170, 150, 100, 51);

        BTNo3.setBackground(new java.awt.Color(204, 0, 0));
        BTNo3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTNo3.setText("NO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNo3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNo3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        BTNo3.setVisible(false);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(70, 110, 84, 59);

        BTNo4.setBackground(new java.awt.Color(204, 0, 0));
        BTNo4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTNo4.setText("NO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BTNo4)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNo4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BTNo4.setVisible(false);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(70, 40, 99, 51);

        BTNo1.setBackground(new java.awt.Color(204, 0, 0));
        BTNo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTNo1.setText("NO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BTNo1)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNo1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8);
        jPanel8.setBounds(167, 11, 121, 57);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(58, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        // Add mouse listeners to change button visibility on hover
        BTNo1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                BTNo1.setVisible(false);
                BTNo2.setVisible(true);
            }
        });

        BTNo2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                BTNo2.setVisible(false);
                BTNo3.setVisible(true);
            }
        });

        BTNo3.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                BTNo3.setVisible(false);
                BTNo4.setVisible(true);
            }
        });

        BTNo4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                BTNo4.setVisible(false);
                BTNo5.setVisible(true);
            }
        });

        BTNo5.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                BTNo5.setVisible(false);
                BTNo6.setVisible(true);
            }
        });

        BTNo6.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                BTNo6.setVisible(false);
                BTNo1.setVisible(true);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BTSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSiActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Así es, este alumno se merece un 10", tituloAlarma, JOptionPane.DEFAULT_OPTION);
        System.exit(0);
    }//GEN-LAST:event_BTSiActionPerformed

    private void BTNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNo1ActionPerformed
        BTNo2.setVisible(true);
        BTNo1.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_BTNo1ActionPerformed

    private void BTNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNo2ActionPerformed
        // TODO add your handling code here:
        BTNo2.setVisible(false);
        BTNo3.setVisible(true);
    }//GEN-LAST:event_BTNo2ActionPerformed

    private void BTNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNo3ActionPerformed
        // TODO add your handling code here:
        BTNo3.setVisible(false);
        BTNo4.setVisible(true);
    }//GEN-LAST:event_BTNo3ActionPerformed

    private void BTNo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNo4ActionPerformed
        // TODO add your handling code here:
        BTNo4.setVisible(false);
        BTNo5.setVisible(true);
    }//GEN-LAST:event_BTNo4ActionPerformed

    private void BTNo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNo5ActionPerformed
        // TODO add your handling code here:
        BTNo5.setVisible(false);
        BTNo6.setVisible(true);
    }//GEN-LAST:event_BTNo5ActionPerformed

    private void BTNo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNo6ActionPerformed
        // TODO add your handling code here:
        BTNo6.setVisible(false);
        BTNo1.setVisible(true);
    }//GEN-LAST:event_BTNo6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNo1;
    private javax.swing.JButton BTNo2;
    private javax.swing.JButton BTNo3;
    private javax.swing.JButton BTNo4;
    private javax.swing.JButton BTNo5;
    private javax.swing.JButton BTNo6;
    private javax.swing.JButton BTSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
