-- Seleccionar la base de datos
USE empresa;

-- Crear tabla ACCOUNT solo si no existe
CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNTNO INT NOT NULL AUTO_INCREMENT,
    EMPNO INT NOT NULL,
    AMOUNT DECIMAL(19, 4) NOT NULL,
    PRIMARY KEY (ACCOUNTNO),
    FOREIGN KEY (EMPNO) REFERENCES EMP(EMPNO)
) ENGINE=InnoDB;

-- Eliminar restricción si existe y crear tabla ACC_MOVEMENT solo si no existe
CREATE TABLE IF NOT EXISTS ACC_MOVEMENT (
    ACCOUNT_MOV_ID INT NOT NULL AUTO_INCREMENT,
    ACCOUNT_ORIGIN_ID INT NOT NULL,
    ACCOUNT_DEST_ID INT NOT NULL,
    AMOUNT DECIMAL(19, 4) NOT NULL,
    DATETIME DATETIME NOT NULL,
    PRIMARY KEY (ACCOUNT_MOV_ID),
    FOREIGN KEY (ACCOUNT_ORIGIN_ID) REFERENCES ACCOUNT(ACCOUNTNO),
    FOREIGN KEY (ACCOUNT_DEST_ID) REFERENCES ACCOUNT(ACCOUNTNO)
) ENGINE=InnoDB;