
USE empresa;

CREATE TABLE IF NOT EXISTS PROJECT (
    PROJNO INT AUTO_INCREMENT NOT NULL,
    PROJNAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (PROJNO)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PROJECT_EMP (
    PROJECTNO INT NOT NULL,
    EMPNO INT NOT NULL,
    PRIMARY KEY (PROJECTNO, EMPNO),
    FOREIGN KEY (EMPNO) REFERENCES EMP(EMPNO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (PROJECTNO) REFERENCES PROJECT(PROJNO) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
